services:
  - type: web
    name: chatbot-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
